name: Docker Image CI

on: [push]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: ./build.sh
    - name: Push the Docker image
      run: ./push.sh
